### ISSUE TITLE
RPC-connection problems

### ISSUE THREAD

**Issue by coinflow** [Rav3nPL/p2pool-rav#103]
Hi Rav3enPL,

after upgrading the Mooncoin-daemon to the latest version, P2Pool seems to have difficulties connecting to the daemon. mooncoindev is pointing at p2pool as the culprit, as the new wallet is based on a 0.10-Litecoin-version, which has deprecated getwork and getblocktemplate ...?

See: https://github.com/mooncoindev/mooncoin/issues/2

Any idea? As there are working Litecoin P2Pool-nodes, I assume it could not be too hard to make it work for Mooncoin again, right?

Thanks and best regards

coinflow

**Comment by Rav3nPL** [comment]
I`ll look into it, just need compile and run/sync deamon.

**Comment by coinflow** [comment]
Thanks. Have you checked it already?

**Comment by coinflow** [comment]
Check this, too: https://github.com/mooncoindev/mooncoin/commit/2688e5883fd54a2782876965689e5a929d1771a5

--> https://bitcointalk.org/index.php?topic=1733963.msg18446318#msg18446318

**Comment by Rav3nPL** [comment]
gut pull and try "./run_p2pool.py --net Mooncoin" (capital "M")
I have no script miner to check it.

**Comment by coinflow** [comment]
Looking at the commit (https://github.com/Rav3nPL/p2pool-rav/commit/4a4aa6abce20737d93f152e17d00fa7ac71a6412)  it is essentially only changing the filenames to capital "M", or did I miss something else?

After doing this and restarting via ./run_p2pool.py --net Mooncoin there still is the message:
"Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!"

Any other idea what could be the problem?

**Comment by Rav3nPL** [comment]
Not only filenames.
New daemon is using ~/.Mooncoin (not ~/.mooncoin) directory and Mooncoin.conf (not mooncoin.conf), so .py files need to search another file in another place.

**Comment by coinflow** [comment]
Yes, I know about that. The new daemon changed naming-"conventions".
So the daemon itself starts fine on the system and uses the config-file. But when p2pool starts, it throws the message above. Hence my question whether the only changes you made to the p2pool-repository are the renaming of the files two network/mooncoin.py to Mooncoin.py, since I could not find any other commit in your rep to check against ...

**Comment by Rav3nPL** [comment]
There is something wrong on your side then, P2Pool is staring on my node w/o any errors.

**Comment by coinflow** [comment]
Thanks.
Then I'll check that again. Strange thing is, that I never had any problems with other coins and the older versions of Mooncoin (just did an update and it worked). But according to your conclusion, the problem is not p2pool as such, like mooncoindev stated (see the linked issue above)?
Do you have an IP-address or URL of your p2pool-node to countercheck functionality with a miner?

**Comment by Rav3nPL** [comment]
try rav3n.dtdns.net:9664


2017-04-07 23:21 GMT+02:00 coinflow <notifications@github.com>:

**Comment by coinflow** [comment]
Now I've simply pulled the whole repository again, replaced web-static folder with the old one (modified from blixnood's: https://github.com/blixnood), et voilà: it works! :-)

See the Mooncoin P2Pool-scanner, reflecting the nodes: http://5.45.105.66

Thanks again for your help.

**Comment by mooncoincore** [comment]
@coinflow works now? can you explain where was the issue? you just replace the webstatic folder?

**Comment by coinflow** [comment]
I have replaced web-static folder with a slightly modified (only the contents) of blixnood (not available anymore on GitHub, as it seems), But the original one from Rav3n should work fine, too. This one is nice, too: https://github.com/hardcpp/P2PoolExtendedFrontEnd
With blixnoods today I encountered this error in the screen -r-window: https://github.com/p2pool/p2pool/issues/138
As Rav3n also posted in that issue, maybe he can give us a hint on how to change the code in the other frontends ...?

**Comment by mooncoincore** [comment]
It's not working.. 
miner report in http://5.45.105.66 found 1345 blocks in 39 seconds.
also i saw this in pool site
Expected time to block | 4.0200000000000005e+56 hours
From wallet rpc i got right values from getinfo, getdifficulty, etc.
Also the same happens with unomp and in their soft report a very weird diff(3.503059897978045e+63).
Something is wrong with wallet and pool communication..

**Comment by coinflow** [comment]
The backend reported "Got Share!" over and over again, not "Got Block!". Are you sure you are connecting with a Scrypt-miner?

**Comment by Rav3nPL** [comment]
Closing, lets use ONE therad: https://github.com/Rav3nPL/p2pool-rav/issues/105
