### ISSUE TITLE
[MOON] Antminer report DOA shares and false Found Blocks

### ISSUE THREAD

**Issue by mooncoincore** [Rav3nPL/p2pool-rav#106]
Hi,
I'm the new mooncoin dev and i tried the new wallet.
when i add antminer in pool, i see valid shares and no invalid.
In the same time in antminer reported few thousands blocks( Found Blocks ) and thousands dead on arrival shares.
Is this a bug or issue from the pool software?

**Comment by Rav3nPL** [comment]
What antminer model?
What config you set on miner side?
What P2Pool log shows?

**Comment by mooncoincore** [comment]
I will close it because is the same with #105
